### ISSUE TITLE
Handling for UniqueConstraintException is correct ?

### ISSUE THREAD

**Issue by kazuki43zoo** [domaframework/doma-spring-boot#12]
Currently, `UniqueConstraintException` is handled at two places.

1. https://github.com/domaframework/doma-spring-boot/blob/master/doma-spring-boot-autoconfigure/src/main/java/org/seasar/doma/boot/autoconfigure/DomaPersistenceExceptionTranslator.java#L52-L54

2. https://github.com/domaframework/doma-spring-boot/blob/master/doma-spring-boot-autoconfigure/src/main/java/org/seasar/doma/boot/autoconfigure/DomaPersistenceExceptionTranslator.java#L60-L62

Need both ?

**Comment by kazuki43zoo** [comment]
It might be better to change the order as follow.

Before:
```java
		// ...
		if (ex.getCause() instanceof SQLException) {
			SQLException e = (SQLException) ex.getCause();
			String sql = null;
			if (ex instanceof SqlExecutionException) {
				sql = ((SqlExecutionException) ex).getRawSql();
			}
			else if (ex instanceof UniqueConstraintException) {
				sql = ((UniqueConstraintException) ex).getRawSql();
			}
			return translator.translate(ex.getMessage(), sql, e);
		}
		if (ex instanceof OptimisticLockException) {
			return new OptimisticLockingFailureException(ex.getMessage(), ex);
		}
		// ...
```
After:
```java
		// ...
		else if (ex instanceof UnknownColumnException
				|| ex instanceof ResultMappingException) {
			return new TypeMismatchDataAccessException(ex.getMessage(), ex);
		}
		if (ex.getCause() instanceof SQLException) {
			SQLException e = (SQLException) ex.getCause();
			String sql = null;
			if (ex instanceof SqlExecutionException) {
				sql = ((SqlExecutionException) ex).getRawSql();
			}
			else if (ex instanceof UniqueConstraintException) {
				sql = ((UniqueConstraintException) ex).getRawSql();
			}
			return translator.translate(ex.getMessage(), sql, e);
		}

		return new UncategorizedDataAccessException(ex.getMessage(), ex) {
		};
```

What do you think ?

**Comment by kazuki43zoo** [comment]
I've tried test case that a unique constraint occur.

* https://github.com/kazuki43zoo/doma-spring-boot/commit/e5265ba5fcbaa4f2cc03b9f51f1499431b6fa180

In this case, unique constraint error is handled by `SQLExceptionTranslator `(at "1").
Probably, "2" is dead code in DOMA's default behavior.

**Comment by kazuki43zoo** [comment]
I've changed handling order for enable the "2" and removed the "1" because it has become a dead code.
I've submitted the gh-13.

**Comment by making** [comment]
Thanks. I'll look into it.
