### ISSUE TITLE
In multi-thread , SelectOptions#getCount  gives wrong result

### ISSUE THREAD

**Issue by kbhrs** [domaframework/doma-spring-boot#17]
test code

```
    @Test
    public void getCountrySingleThread() throws Exception {
        for (int i = 0; i < L_MAX; i++) {
            getCountrySub("getCountrySingleThread(" + i + ")");
        }
    }
    @Test
    public void getCountryMultiThread() throws Exception {
        IntStream.range(0, L_MAX)
                .parallel()
                .forEach(i -> getCountrySub("getCountryMultiThread(" + i + ")"));
    }
    private void getCountrySub(String message) {
        SelectOptions options = SelectOptions.get().count();
        List<CountryEntity> result = countryDao.select(options);
        assertThat("result.size()", result.size(), is(4));
        assertThat("options.getCount()[" + message + "]", options.getCount(), is(4L));
    }
```

Test gives me the following error

```
Caused by: java.lang.AssertionError: options.getCount()[getCountryMultiThread(92)]
Expected: is <4L>
     but: was <1L>
```
- [assertThat("result.size()", result.size(), is(4));] was not an error. Ｉｔ is my expected.
- In [@Test getCountrySingleThread] , error did not occur.
- In Doma (without Spring boot) with multi-thread,  error did not occur.

Detail and Test Code:
https://github.com/kbhrs/DomaSpringBootMultiThreadTest20160918

Do you have a solution?

**Comment by kbhrs** [comment]
Additional Information
* The above-mentioned issue has confirmed with the MySQL5.6. (But with Doma (without Spring boot) , error did not occur.)
* NEW: With SQL Server2016, the error did not occur.

**Comment by making** [comment]
Springなしの方はトランザクション管理しているけど、Springありの方トランザクション管理していないので、Springありの方もトランザクション管理すると同じ結果になりません？

**Comment by kbhrs** [comment]
ご指摘ありがとうございます。
ご指摘通りに Spring でトランザクションを有効にした以下のソースでテスト通りました。

````
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = DomaCountTestApplication.class)
public class DomaSpringTest {
    private static int L_MAX = 100;

    @Autowired
    DomaSpringTransactionalTest domaSpringTransactionalTest;

    @Test
    public void getCountryMultiThread_di_tx() throws Exception {
        IntStream.range(0, L_MAX)
                .parallel()
                .forEach(i -> domaSpringTransactionalTest.getCountrySub("getCountryMultiThread_tx(" + i + ")"));
    }
}

@Component
class DomaSpringTransactionalTest {
    @Autowired
    CountrySpringDao countryDao;

    @Transactional
    public void getCountrySub(String message) {
        SelectOptions options = SelectOptions.get().count();
        List<CountryEntity> result = countryDao.select(options);
        assertThat("result.size()", result.size(), is(4));
        assertThat("options.getCount()[" + message + "]", options.getCount(), is(4L));
    }
}
````

上記の実装変更でテストが成功するのは
「（少なくともMySQLでは、） SelectOptions＃getCount は、getCount 対象のselect と同一のトランザクションで実行する必要がある」
というのが理由だと考えたのですが、
Spring なしの DOMA で以下のテストも通ってしまい考えた理由の裏付けができなくて困っています。
理解が間違っている点などお気づきでしたら教えていただきたいのです。

````
    @Test
    public void getCountryMultiThread_requiresNew() throws Exception {
        IntStream.range(0, L_MAX)
                .parallel()
                .forEach(i -> getCountrySub_requiresNew("getCountryMultiThread_requiresNew(" + i + ")"));
    }

    private void getCountrySub_requiresNew(String message) {
        CountryDomaDao countryDao = new CountryDomaDaoImpl(AppConfig.singleton());
        TransactionManager tm = AppConfig.singleton().getTransactionManager();
        try {
            SelectOptions options = SelectOptions.get().count();
            tm.requiresNew(() -> {
                List<CountryEntity> result = countryDao.select(options);
                assertThat("result.size()", result.size(), is(4));
            });
            tm.requiresNew(() -> {
                assertThat("options.getCount()[" + message + "]", options.getCount(), is(4L));
            });
        } catch (JdbcException e) {
            throw new RuntimeException("MySQL接続エラー。com.example.AppConfig のjavaソースに記載されているdb接続情報を確認してください", e);
        }
    }
````
※ 正しく件数を取得してエラーになっていないのか？タマタマ同じ件数だからエラーになっていないのか？は未精査ですが、
少なくともSpringとは違いエラーにならないです。

**Comment by making** [comment]
"Spring なしの DOMA で以下のテスト"の方トランザクションがコミットされているから問題ないのでは。

>「（少なくともMySQLでは、） SelectOptions＃getCount は、getCount 対象のselect と同一のトランザクションで実行する必要がある」

こういう制約というより、トランザクションの分離レベルの話かと。


flywayに流すスクリプトの最後にcommitを入れて、`@Transactional`外すとテスト成功します？

**Comment by kbhrs** [comment]
> flywayに流すスクリプトの最後にcommitを入れて、@Transactional外すとテスト成功します？

成功しませんでした。

**Comment by kbhrs** [comment]
昨日は夜遅くにコメントありがとうございました。
コメントを参考に自分で調べてみた結果、自己満足の色が強いですが、一応、腑に落ちたのでご報告させていただきます。

### 結論
* MySQL での検索結果取得に使用している select found rows() は、直前に実行した検索SQLの結果件数を返す仕様だと思われます。
	* 公式情報は  https://dev.mysql.com/doc/refman/5.6/ja/information-functions.html#function_found-rows だと思うのですが、
	select found rows() の前に他の処理が入った場合などの言及がありませんので推測です。
* Spring かつ @Transactional なしのケースで、AssertionError が発生するケースでは メインの検索 と 件数取得の検索が別のトランザクションインスタンスで実行されていました。
	* 別のトランザクションで実行された場合、select found rows() の「直前のSQL」は、メイン検索にはならない（わかりようがない）ので、想定外の値を返すのは合点がいく。
	* これを回避するには @Transactional で同じトランザクションになるように制御する必要がある。
* Spring なしかつ、メインの検索処理と件数取得の検索を 異なる TrasactionManager#requiresNew で実行した場合、同じトランザクションインスタンスが使用されていました。
	* なので select found rows() の「直前のSQL」が、想定する メインの検索処理 になっているので想定通りの値を返す。

### 詳細
####  Spring かつ @Transactional なしのケースで、AssertionError が発生するケースで メインの検索 と 件数取得の検索時のトランザクションインスタンスの確認
再掲：Spring かつ @Transactional なしのケースのテストコード
````
    @Test
    public void getCountryMultiThread() throws Exception {
        IntStream.range(0, L_MAX)
                .parallel()
                .forEach(i -> getCountrySub("getCountryMultiThread(" + i + ")"));
    }
    private void getCountrySub(String message) {
        SelectOptions options = SelectOptions.get().count();
        List<CountryEntity> result = countryDao.select(options);
        assertThat("result.size()", result.size(), is(4));
        assertThat("options.getCount()[" + message + "]", options.getCount(), is(4L)); // これがエラーになる場合がある
    }
````

これをエラーになるケースとならないケースを Dynatrace Application Monitoring （ https://www.dynatrace.com/ja/products/application-monitoring.html ）というツールで解析した結果、
エラーになるケースでは、トランザクションインスタンスが異なっていることが確認できた（添付画像）。

![transactioninstance](https://cloud.githubusercontent.com/assets/11334076/18623562/d75ea4a4-7e79-11e6-9bb2-57a46ee85429.png)

#### Spring なしかつ、メインの検索処理と件数取得の検索を 異なる TrasactionManager#requiresNew で実行した場合
再掲：Spring なしかつ、メインの検索処理と件数取得の検索を 異なる TrasactionManager#requiresNew で実行
````
    @Test
    public void getCountryMultiThread_requiresNew() throws Exception {
        IntStream.range(0, L_MAX)
                .parallel()
                .forEach(i -> getCountrySub_requiresNew("getCountryMultiThread_requiresNew(" + i + ")"));
    }
    private void getCountrySub_requiresNew(String message) {
        CountryDomaDao countryDao = new CountryDomaDaoImpl(AppConfig.singleton());
        TransactionManager tm = AppConfig.singleton().getTransactionManager();
        try {
            SelectOptions options = SelectOptions.get().count();
            tm.requiresNew(() -> {
                List<CountryEntity> result = countryDao.select(options);
                assertThat("result.size()", result.size(), is(4));
            });
            tm.requiresNew(() -> {
                assertThat("options.getCount()[" + message + "]", options.getCount(), is(4L));
            });
        } catch (JdbcException e) {
            throw new RuntimeException("MySQL接続エラー。com.example.AppConfig のjavaソースに記載されているdb接続情報を確認してください", e);
        }
    }
````

* 当初は「別トランザクションになると件数取得SQLの結果が正しくなくなる」ならば、上記のソースコードもそれに該当すると思い getCount のアサーションでエラーになることを期待した。
* 前述の Dynatrace Application Monitoring で確認したところ、メインの検索処理と件数取得の検索は毎回 同じトランザクションインスタンス だった（エビデンス省略）。
	* 差異としては、「Spring かつ・・・」の方は com.mysql.jdbc.JDBC4Connection のインスタンスだったのに対して、「Spring なし・・・」の方は「org.seasar.doma.jdbc.tx.LocalTransactionConnection」のインスタンスだった
	* そもそも TransactionManager が違う
* org.seasar.doma.jdbc.tx.LocalTransactionManager の実装を見てみたところ、requiresNew の場合でも、transaction インスタンスは使いまわす実装になっている。結果、 select found rows() の「直前のSQL」が、想定する メインの検索処理 になっているので想定通りの値を返す。
	* 具体的には 「requiresNewInternal」「executeInTransaction」あたり

よって、Springなしでも getCount が異なる値を出すケースを作りたかったのですが、難しそうなので、これにて終了。

### まとめ
doma-spring-boot  で SelectOptions#getCount を使う場合は、元の検索ＳＱＬと同一のトランザクションで実行されるように制御する必要がある。具体的には @Transactional を使って同一のトランザクションになるようにする。

以上です。
