### ISSUE TITLE
Is doma-spring-boot planning to support Spring Boot 2.0?

### ISSUE THREAD

**Issue by gloryof** [domaframework/doma-spring-boot#27]
Spring Boot 2.0 was released at March 1st.
https://spring.io/blog/2018/03/01/spring-boot-2-0-goes-ga

Maybe, doma-spring-boot is support until 1.5.7.RELEASE.
Is doma-spring-boot planning to support Spring Boot 2.0?

**Comment by making** [comment]
any issue?

**Comment by gloryof** [comment]
Now, problem is not happened.

doma-spring-boot dependency version is 1.5.
I think that doma-spring-boot is not supported version 2.0.

I'm sorry if my thought is mistake.
