### ISSUE TITLE
solution for spring boot 2.1.X

### ISSUE THREAD

**Issue by bitoogii** [domaframework/doma-spring-boot#35]
Is there any solution for 

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.***.dao.SampleDao' in your configuration.

Just followed on Spring boot 2.1.0. I know it works on 1.5.x but I want to use in 2.1.*

**Comment by backpaper0** [comment]
Please show me the source code that is problematic.

**Comment by bitoogii** [comment]
I will share my source tommorow. Anyway I followed this.
https://end0tknr.hateblo.jp/entry/20190104/1546562341.

**Comment by backpaper0** [comment]
It seems that 'SampleDaoImpl' is not generated by annotation processor.

In that blog, it has the following script in build.gradle:

> annotationProcessor("org.seasar.doma.boot:doma-spring-boot-starter:1.1.1")

Please change this as follows:

```
annotationProcessor("org.seasar.doma:doma:2.23.0")
```

**Comment by bitoogii** [comment]
https://github.com/bitoogii/sample_rest
I made sample configuration here.
I`m using eclipse and I can`t find any annotation processor in Eclipse settings.

**Comment by backpaper0** [comment]
It's not enough settings in build.gradle.
Please update build.gradle with reference to the following diff:

```diff
diff --git a/build.gradle b/build.gradle
index de9289c..fe82e94 100644
--- a/build.gradle
+++ b/build.gradle
@@ -29,5 +29,11 @@ dependencies {
     compile("org.seasar.doma.boot:doma-spring-boot-starter:1.1.0")
        compile(group: 'org.postgresql', name: 'postgresql')
        compileOnly 'org.projectlombok:lombok'
+       annotationProcessor 'org.projectlombok:lombok'
+       compile 'org.seasar.doma:doma:2.23.0'
+       annotationProcessor 'org.seasar.doma:doma:2.23.0'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
 }
+
+processResources.destinationDir = compileJava.destinationDir
+compileJava.dependsOn processResources
```

What is the version of Eclipse?

**Comment by bitoogii** [comment]
Sorry. Still same error.
I`m using plain pleiades
Version: Photon Release (4.8.0)
Build id: 20180619-1200

**Comment by backpaper0** [comment]
Do you read following document?
https://doma.readthedocs.io/en/stable/build/#eclipse-build
