### ISSUE TITLE
Use template engine standalone

### ISSUE THREAD

**Issue by NicklasWallgren** [domaframework/doma-spring-boot#55]
Is it possible to use the SQL template engine as a standalone unit. We're currently using https://github.com/OpenGamma/ElSql as a SQL template engine, but the syntax doesn't meet our requirements.

Thanks.

**Comment by backpaper0** [comment]
This issue is better to be created on by [Doma](https://github.com/domaframework/doma).
This repository only provides integration between Doma and Spring Boot.
It is [Doma](https://github.com/domaframework/doma) that has the SQL template engine.

**Comment by NicklasWallgren** [comment]
Alright, thanks
