### ISSUE TITLE
[v1.2.x] Fix the central repository URL to https

### ISSUE THREAD

**Issue by imunew** [domaframework/doma-spring-boot#78]
## The central repository moved to https
Our project use `doma-spring-boot` version `1.2.1`.
The following build error occurs.

> [ERROR] Failed to execute goal on project xxxxxx: Could not resolve dependencies for project xxxxxx: Failed to collect dependencies at org.seasar.doma.boot:doma-spring-boot-starter:jar:1.2.1: Failed to read artifact descriptor for org.seasar.doma.boot:doma-spring-boot-starter:jar:1.2.1: Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:1.5.22.RELEASE from/to central (http://repo1.maven.org/maven2/): Transfer failed for http://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/1.5.22.RELEASE/spring-boot-dependencies-1.5.22.RELEASE.pom 501 HTTPS Required -> [Help 1]

## Fix the central repository and Release v1.2.2
So, please fix the central repository url and Release v1.2.2.

https://github.com/domaframework/doma-spring-boot/blob/1.2.1/pom.xml#L207

```xml
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>Maven Central repository</name>
            <url>https://repo1.maven.org/maven2/</url> // http => https
        </repository>
```

**Comment by backpaper0** [comment]
Thanks for using doma-spring-boot!

I try build with [this project (branch name is issue/78)](https://github.com/backpaper0/doma-spring-boot-demo/tree/issues/78) that use doma-spring-boot 1.2.1 and got `BUILD SUCCESS` (Build command is `./mvnw clean package -Dmaven.repo.local=./.m2/repository`).

Please provide me the minimum source code that reproduces this issue.
And tell me JDK version and Maven version.
